In [2]:
import pandas as pd, sqlite3
con = sqlite3.connect("../grocery.db")

In [4]:
pd.read_sql("""
SELECT strftime('%w', date) AS dow, ROUND(AVG(total_sales)) AS avg_daily_sales
FROM (SELECT date, SUM(sales) AS total_sales FROM train GROUP BY date)
GROUP BY dow ORDER BY dow
""", con)

  dow  avg_daily_sales
0   0         825218.0
1   1         617543.0
2   2         569926.0
3   3         593245.0
4   4         505269.0
5   5         579574.0
6   6         772206.0

In [6]:
daily = pd.read_sql("SELECT date, SUM(sales) AS total_sales FROM train GROUP BY date", con)
daily["date"] = pd.to_datetime(daily["date"])
daily["yr"] = daily["date"].dt.year
daily["month"] = daily["date"].dt.month

full = daily[daily["yr"] < 2017].copy()
full["rel"] = full["total_sales"] / full.groupby("yr")["total_sales"].transform("mean")
full.groupby("month")["rel"].mean().round(3)

month
1     0.907
2     0.836
3     0.950
4     0.886
5     0.899
6     0.952
7     1.017
8     0.949
9     1.074
10    1.068
11    1.111
12    1.349
Name: rel, dtype: float64

In [7]:
d = daily[daily["date"] < "2017-08-01"].copy()   # drop the partial last month
d["dow"] = d["date"].dt.dayofweek
d["dom"] = d["date"].dt.day
d["rel"] = d["total_sales"] / d.groupby(["yr", "month", "dow"])["total_sales"].transform("mean")
d.groupby("dom")["rel"].mean().round(3)

C:\Users\nickl\AppData\Local\Temp\ipykernel_1928\2199673999.py:2: Pandas4Warning: Series.dt.dayofweek is deprecated and will be removed in a future version. Use Series.dt.day_of_week instead.
  d["dow"] = d["date"].dt.dayofweek

dom
1     1.091
2     1.138
3     1.112
4     1.102
5     1.087
6     1.063
7     1.050
8     0.994
9     0.945
10    0.935
11    0.956
12    0.967
13    0.968
14    0.967
15    0.974
16    0.983
17    0.980
18    1.000
19    0.994
20    1.021
21    1.016
22    0.980
23    0.958
24    0.951
25    0.938
26    0.951
27    0.948
28    0.967
29    0.958
30    0.974
31    1.038
Name: rel, dtype: float64

In [5]:
pd.read_sql("""
SELECT strftime('%d', date) AS day_of_month, ROUND(AVG(total_sales)) AS avg_daily_sales
FROM (SELECT date, SUM(sales) AS total_sales FROM train GROUP BY date)
GROUP BY day_of_month ORDER BY day_of_month
""", con)

   day_of_month  avg_daily_sales
0            01         712046.0
1            02         743478.0
2            03         716647.0
3            04         699982.0
4            05         683849.0
5            06         664790.0
6            07         648920.0
7            08         627407.0
8            09         623098.0
9            10         603813.0
10           11         606681.0
11           12         610212.0
12           13         605309.0
13           14         598778.0
14           15         621449.0
15           16         645074.0
16           17         633378.0
17           18         633351.0
18           19         624548.0
19           20         636039.0
20           21         633149.0
21           22         628548.0
22           23         637389.0
23           24         615149.0
24           25         581805.0
25           26         597870.0
26           27         586053.0
27           28         596308.0
28           29         616257.0
29           30         654639.0
30           31         694164.0